services:
  nginx:
    build:
      context: images/nginx
    restart: always
    environment:
      - NGINX_PORT=8080
      - NGINX_SSL_PORT=443
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
    ports:
      - '${NGINX_PUBLIC_PORT:-8080}:8080'
      - '${NGINX_SSL_PUBLIC_PORT:-443}:443'
    volumes:
      - ./www:/var/www/web
  php:
    image: webpress/php:8.2-fpm-ioncube
    restart: unless-stopped
    volumes:
      - ./www:/var/www/web
    environment:
      - TZ=${TZ:-Asia/Ho_Chi_Minh}
      - MAIL_MAILER=${MAIL_MAILER:-smtp}
      - MAIL_HOST=${MAIL_HOST:-sandbox.smtp.mailtrap.io}
      - MAIL_PORT=${MAIL_PORT:-2525}
      - MAIL_USERNAME=${MAIL_USERNAME:-a77eb347161419}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-e19eac3474863a}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-tls}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-from@example.com}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-Webpress}
      - DB_HOST=${DB_HOST:-database}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_ROOT_PASSWORD:-secret}
      - APP_KEY=${APP_KEY:-base64:PJWkmeK3NF9/gfRC+BjSimvQYT1qblkLugmvznRaZyk=}
      - LOG_CHANNEL=${WEBPRESS_LOG_CHANNEL:-stack}
      - APP_NAME=${WEBPRESS_APP_NAME:-Webpress}
      - APP_ENV=${WEBPRESS_APP_ENV:-local}
      - JWT_SECRET=${JWT_SECRET:-base64:g2pK3uGDBJtEswoTD4DqSwehD1CQDj47+lIynfjPa08=}
      - JWT_TTL=${JWT_SECRET:-2592000}
      - API_PREFIX=${API_PREFIX:-api}
      - API_VERSION=${API_VERSION:-v1}
      - API_NAME=${API_NAME:-webpress}
      - API_DEBUG=${API_DEBUG:-true}
      - WEBPRESS_AWS_TRANSLATION_API_URL=${WEBPRESS_AWS_TRANSLATION_API_URL:-https://execute-api.webpress.vn/dev/webpress/aws/translate-service}
      - WEBPRESS_AWS_TRANSLATION_API_KEY=${WEBPRESS_AWS_TRANSLATION_API_KEY:-secret}
      - WEBPRESS_AWS_STORE_API_URL=${WEBPRESS_AWS_STORE_API_URL:-https://execute-api.webpress.vn/dev/webpress/aws/store-service}
      - WEBPRESS_AWS_STORE_API_KEY=${WEBPRESS_AWS_STORE_API_KEY:-secret}

  database:
    image: '${MYSQL_IMAGE:-mysql:8.0}'
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --disable-log-bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=konga
      - MYSQL_USER=konga
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - dbdata:/var/lib/mysql
      - ./www:/var/www/web
    ports:
      - '${DB_PUBLIC_PORT:-33306}:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - 'PMA_HOST=database'
      - 'UPLOAD_LIMIT=${PHPMYADMIN_UPLOAD_LIMIT:-300000000}'
      - 'PMA_ABSOLUTE_URI=http://localhost:${PHPMYADMIN_PUBLIC_PORT:-8089}'
    ports:
      - '${PHPMYADMIN_PUBLIC_PORT:-8089}:80'
volumes:
  dbdata:
    external: true
